' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/25/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\Bmw\Boîte de vitesses\Boîte de vitesses.SLDASM", 2)
Set Part = swApp.ActivateDoc ("Boîte de vitesses")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.SelectByID "Carter équipé-1@Boîte de vitesses/Chassis-1@Carter équipé", "COMPONENT", 0, 0, 0
Part.SelectByID "Carter équipé-1@Boîte de vitesses/Articulation-1@Carter équipé", "COMPONENT", 0, 0, 0
Part.EditDelete
Part.SelectByID "Carter équipé-1@Boîte de vitesses", "COMPONENT", 0, 0, 0
Part.SelectByID "Carter équipé-1@Boîte de vitesses", "COMPONENT", 0, 0, 0
Part.EditAssembly
Part.ClearSelection
Part.SelectByID "Carter équipé-1@Boîte de vitesses/Articulation-1@Carter équipé", "COMPONENT", 0, 0, 0
Part.EditDelete
Part.EditAssembly
Part.ViewZoomtofit2
' MSGBOX
' Certains des modèles référencés dans ce document ont été modifiés. Ils doivent être enregistrés lorsque le document est enregistré.
' 		Enregistrer le document et les modèles référencés maintenant ?

Part.Save2 FALSE
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
