' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/11/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\BMW\Boîte de vitesses\Boîte de vitesses bloc.SLDASM", 2)
Set Part = swApp.ActivateDoc ("Boîte de vitesses bloc")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.SelectByID "Arbre d'entrée-1@Boîte de vitesses bloc/Pignon  virtuel 22 dents-1@Arbre d'entrée", "COMPONENT", 0, 0, 0
Part.ClearSelection
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.Save2 FALSE
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
