' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/26/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\BMW\Renvoi d'angle\carter renvoi d'angle\Carter renvoi d'angle.SLDASM", 2)
' MSGBOX
' N'a pas pu trouver le fichier C:\BMW\Renvoi d'angle\carter droit\carter4.SLDPRT. Voulez-vous le chercher vous-même ?

Set Part = swApp.ActivateDoc ("Carter renvoi d'angle")
' MSGBOX
' Certains des modèles référencés dans ce document ont été modifiés. Ils doivent être enregistrés lorsque le document est enregistré.
' 		Enregistrer le document et les modèles référencés maintenant ?

Part.Save2 FALSE
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
