' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/19/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 30205.SLDASM", 2)
Set Part = swApp.ActivateDoc ("Roulement 30205")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = Nothing
swApp.CloseDoc "Roulement 30205"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 30205.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 30205")
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' N'a pas pu trouver le fichier C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Bague ext.SLDPRT. Voulez-vous le chercher vous-même ?

Set Part = Nothing
swApp.CloseDoc "Roulement 30205"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 30205.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 30205")
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' N'a pas pu trouver le fichier C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Bague ext.SLDPRT. Voulez-vous le chercher vous-même ?

Set Part = Nothing
swApp.CloseDoc "Roulement 30205"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Roulement 30205.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 30205")
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' N'a pas pu trouver le fichier C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Bague ext.SLDPRT. Voulez-vous le chercher vous-même ?

Part.Save2 FALSE
Set Part = Nothing
swApp.CloseDoc "Roulement 30205"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 25-52.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 25-52")
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' N'a pas pu trouver le fichier C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Bague ext.SLDPRT. Voulez-vous le chercher vous-même ?

Set Part = Nothing
swApp.CloseDoc "Roulement 25-52"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 25-52.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 25-52")
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' N'a pas pu trouver le fichier C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Bague ext.SLDPRT. Voulez-vous le chercher vous-même ?

Part.Save2 FALSE
Set Part = Nothing
swApp.CloseDoc "Roulement 25-52"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d20\Roulement 20-47.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 20-47")
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.SelectByID "Esquisse1@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.SketchConstraintsDel 7, "sgCOINCIDENT"
Part.SketchConstraintsDel 7, "sgCOINCIDENT"
Part.SketchConstraintsDel 4, "sgUSEEDGE"
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Bague extérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Esquisse1@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.ViewZoomTo2 -0.0275628, 0.0329264, -1.73559e-016, 0.00376438, 0.00781291, 1.8079e-018
Part.SelectByID "Point37", "SKETCHPOINT", -0.014, 0.01640589338312, 0
Part.AndSelectByID "", "SILHOUETTE", -0.01477338920924, 0.01629279028131, 0
Part.AndSelectByID "", "SILHOUETTE", -0.01375417226167, 0.01568126011277, 0
Part.SketchAddConstraints "sgATINTERSECT"
Part.ClearSelection
Part.SelectByID "Line16", "SKETCHSEGMENT", -0.003271294712016, 0.0187698339057, 0
Part.SelectByID "Line15", "SKETCHSEGMENT", -0.00689934525655, 0.01630930987052, 0
Part.SelectByID "Line15", "SKETCHSEGMENT", -0.01020458022069, 0.01636274652405, 0
Part.AndSelectByID "", "SILHOUETTE", -0.01081882745269, 0.01551818540116, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.ViewDisplayHiddengreyed
Part.AndSelectByID "", "SILHOUETTE", -0.003113547329101, 0.01812738078693, 0
Part.AndSelectByID "Point22", "SKETCHPOINT", -0.005146675867768, 0.0198611098125, 0
Part.SketchAddConstraints "sgCOINCIDENT"
Part.ClearSelection
Part.ViewDisplayShaded
Part.ViewZoomtofit2
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Base-Révolution@Cage-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.SketchConstraintsDel 6, "sgCOINCIDENT"
Part.SketchConstraintsDel 6, "sgCOINCIDENT"
Part.SketchConstraintsDel 6, "sgHORIZPOINTS"
Part.SketchConstraintsDel 10, "sgCOLINEAR"
Part.SelectByID "Point9", "SKETCHPOINT", -0.003385649603644, 0, 0
Part.AndSelectByID "", "EDGE", -0.003261334377227, 0.003374571141668, 0.01895190675395
' MSGBOX
' Ne peut pas utiliser cette sélection. Permettre cette sélection aurait créé des conflits de contexte comme mentionné plus tôt.

' MSGBOX
' Les objets sélectionnés ne peuvent pas être convertis en une ligne ou un arc dans le plan esquissé.

Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Base-Révolution@Cage-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.InsertSketch
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.SketchConstraintsDel 1, "sgTANGENT"
Part.SketchConstraintsDel 1, "sgTANGENT"
Part.SketchConstraintsDel 1, "sgCOLINEAR"
Part.InsertSketch
Part.SelectByID "Base-Révolution@Cage-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
Part.ClearSelection
Part.SelectByID "Point10", "SKETCHPOINT", -0.014, 0, 0
Part.AndSelectByID "", "EDGE", -0.01409284728822, 0.003269847849054, 0.01607673576143
Part.SketchAddConstraints "sgCOINCIDENT"
Part.ClearSelection
Part.AndSelectByID "Point9", "SKETCHPOINT", -0.003385649603644, 0, 0
Part.AndSelectByID "", "EDGE", -0.003447619530528, -0.004257080868506, 0.01877337909059
Part.SketchAddConstraints "sgCOINCIDENT"
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.SelectByID "@rouleau-1@Roulement 20-47", "AXIS", -0.04656616832683, 0.008216115292021, 0
Part.AndSelectByID "Line11", "SKETCHSEGMENT", -0.02106959174958, 0.0153752981514, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.SelectByID "Line7", "SKETCHSEGMENT", -0.005705698145796, 0, 0
Part.SketchAddConstraints "sgHORIZONTAL"
Part.ClearSelection
Part.SelectByID "Line7", "SKETCHSEGMENT", -0.00602828080512, 0, 0
Part.SketchConstraintsDel 0, "sgHORIZONTAL"
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0897598
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0841498
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0175642, -0.1122
Part.ActiveView().RotateAboutCenter 0.0263463, -0.11781
Part.ActiveView().RotateAboutCenter 0.0351284, -0.19074
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0729298
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0729298
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0953698
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01683
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0224399
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0617099
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.302939
Part.ActiveView().RotateAboutCenter -0.00439104, 0.359039
Part.ActiveView().RotateAboutCenter -0.0131731, 0.437579
Part.ActiveView().RotateAboutCenter -0.0614746, 0.297329
Part.ActiveView().RotateAboutCenter -0.00878209, 0.16269
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0897598
Part.ActiveView().RotateAboutCenter 0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter 0.114167, 0.1122
Part.ActiveView().RotateAboutCenter 0.0395194, 0.0897598
Part.ActiveView().RotateAboutCenter 0.0219552, 0.0392699
Part.ActiveView().RotateAboutCenter 0.0175642, 0.0392699
Part.SelectByID "@Bague intérieure-1@Roulement 20-47", "AXIS", -0.01513801408913, -0.0003448484225224, -0.002151850978861
Part.AndSelectByID "Line7", "SKETCHSEGMENT", -0.01151342460201, 0, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.InsertSketch
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.SelectByID "Line18", "SKETCHSEGMENT", -0.003181646586676, 0.005435595689362, 0
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.136122, -0.0560999
Part.ActiveView().RotateAboutCenter 0.180033, -0.0224399
Part.ActiveView().RotateAboutCenter 0.0614746, -0.01122
Part.ActiveView().RotateAboutCenter 0.122949, -0.0224399
Part.ActiveView().RotateAboutCenter 0.223943, 0
Part.ActiveView().RotateAboutCenter 0.0395194, 0.01683
Part.ActiveView().RotateAboutCenter 0.118558, 0.0448799
Part.ActiveView().RotateAboutCenter 0.12734, 0.0392699
Part.ActiveView().RotateAboutCenter 0.12734, 0.0785398
Part.ActiveView().RotateAboutCenter 0.0746478, 0.0560999
Part.ActiveView().RotateAboutCenter 0.0351284, 0.01683
Part.ActiveView().RotateAboutCenter 0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01683
Part.ViewZoomTo2 -0.00479772, -0.00180995, -0.0167287, 0.010858, -0.0145365, -0.0167287
Part.AndSelectByID "", "SILHOUETTE", -0.01358550850966, 0.01659025792581, 0.002247270348192
Part.DeSelectByID "", "SILHOUETTE", -0.01355608864441, 0.0164861977117, 0.002201198145997
Part.AndSelectByID "", "EDGE", -0.01333020477551, 0.01655975764218, 0.002442275326146
Part.SketchAddConstraints "sgTANGENT"
Part.ClearSelection
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.158078, -0.0448799
Part.ActiveView().RotateAboutCenter -0.307373, -0.11781
Part.ActiveView().RotateAboutCenter -0.276636, -0.0617099
Part.ActiveView().RotateAboutCenter -0.228334, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0526925, 0.0617099
Part.ActiveView().RotateAboutCenter -0.0614746, 0.241229
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0560999
Part.ActiveView().RotateAboutCenter 0.136122, 0.17952
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0175642, -0.0560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.11781
Part.ActiveView().RotateAboutCenter -0.0614746, -0.0560999
Part.ActiveView().RotateAboutCenter -0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.AndSelectByID "Line17", "SKETCHSEGMENT", 0.004087998561886, -0.004598029085043, 0
Part.ActiveView().RotateAboutCenter -0.0351284, 0
Part.ActiveView().RotateAboutCenter -0.118558, -0.00560999
Part.ActiveView().RotateAboutCenter -0.144904, 0
Part.ActiveView().RotateAboutCenter -0.136122, 0
Part.ActiveView().RotateAboutCenter -0.114167, 0
Part.ActiveView().RotateAboutCenter -0.0658657, 0
Part.ActiveView().RotateAboutCenter -0.0483015, 0
Part.ActiveView().RotateAboutCenter -0.0219552, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0702567, 0.00560999
Part.ActiveView().RotateAboutCenter -0.118558, 0.0560999
Part.ActiveView().RotateAboutCenter -0.114167, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0834298, 0.01683
Part.ActiveView().RotateAboutCenter -0.289809, 0
Part.ActiveView().RotateAboutCenter -0.096603, 0
Part.ActiveView().RotateAboutCenter -0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ViewZoomtofit2
Part.ViewZoomTo2 -0.00790613, 0.0323477, -0.0165917, 0.00563841, 0.0139539, -0.0165917
Part.AndSelectByID "", "EDGE", -0.004014955087428, 0.02059107678991, 0.002926473268118
Part.SketchAddConstraints "sgTANGENT"
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.0953698
Part.ActiveView().RotateAboutCenter -0.00439104, -0.10098
Part.ActiveView().RotateAboutCenter -0.00878209, -0.10098
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0483015, 0
Part.ActiveView().RotateAboutCenter -0.0614746, 0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0307373, 0.01683
Part.ActiveView().RotateAboutCenter 0.0219552, 0.0280499
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.SelectByID "D3@Esquisse4@Cage-1@Roulement 20-47", "DIMENSION", 0.006700968558697, 0.008680008637911, -0.007171138581587
Part.SelectByID "Line10", "SKETCHSEGMENT", 0.002364241122967, -0.001394106731588, 0
Part.ClearSelection
Part.ActiveView().RotateAboutCenter -0.0263463, 0
Part.ActiveView().RotateAboutCenter -0.153687, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0834298, 0
Part.ActiveView().RotateAboutCenter -0.0526925, 0
Part.ActiveView().RotateAboutCenter -0.0790388, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0351284, 0
Part.ActiveView().RotateAboutCenter -0.0526925, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0395194, -0.0897598
Part.ActiveView().RotateAboutCenter -0.0526925, -0.0897598
Part.ActiveView().RotateAboutCenter -0.0351284, -0.0280499
Part.ActiveView().RotateAboutCenter -0.0834298, -0.0280499
Part.ActiveView().RotateAboutCenter -0.0263463, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.100994, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0263463, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ViewZoomTo2 -0.00636543, 0.0109783, -0.0177749, 0.0063407, -0.00897257, -0.0177749
Part.SelectByID "", "FACE", -0.01041661197647, 0.02082767109397, -0.001331725635523
Part.AndSelectByID "Line16", "SKETCHSEGMENT", 0.005649622883421, 0.001908829196239, 0
Part.ViewDisplayHiddengreyed
Part.ViewZoomtofit2
Part.ClearSelection
Part.SelectByID "", "FACE", -0.008390393995597, 0.02123924681035, -0.002771056460035
Part.ClearSelection
Part.ViewDisplayShaded
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0614746, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0351284, 0
Part.ActiveView().RotateAboutCenter -0.0395194, 0
Part.ActiveView().RotateAboutCenter -0.0219552, 0
Part.ActiveView().RotateAboutCenter -0.0395194, 0
Part.ActiveView().RotateAboutCenter -0.0439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0483015, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0526925, 0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0702567, 0
Part.ActiveView().RotateAboutCenter -0.0746478, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0922119, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0483015, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0614746, 0
Part.ActiveView().RotateAboutCenter -0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.114167, 0
Part.ActiveView().RotateAboutCenter -0.122949, 0
Part.ActiveView().RotateAboutCenter -0.0483015, 0
Part.ActiveView().RotateAboutCenter -0.0175642, 0
Part.ActiveView().RotateAboutCenter -0.0219552, 0
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter -0.00878209, -0.12342
Part.ActiveView().RotateAboutCenter -0.0131731, -0.10098
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0673198
Part.ActiveView().RotateAboutCenter -0.0219552, -0.10098
Part.ActiveView().RotateAboutCenter -0.0526925, -0.0617099
Part.ActiveView().RotateAboutCenter -0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0395194, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0526925, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0395194, 0.01683
Part.ActiveView().RotateAboutCenter -0.0526925, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0175642, 0.01122
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0131731, 0
Part.ActiveView().RotateAboutCenter 0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, 0
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0, 0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0617099
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.00878209, 0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0175642, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0897598
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter 0, -0.0280499
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.SelectByID "", "EDGE", -0.003631242800225, 0.02022768880124, -0.002692511990631
Part.SelectByID "", "EDGE", -0.003760620017033, 0.02026557336859, -0.00302781743099
Part.SelectByID "", "EDGE", -0.004033938100577, 0.02023304218466, -0.003310280047884
Part.ClearSelection
Part.SelectByID "Line10", "SKETCHSEGMENT", 0.00522940679976, -0.0001133478740739, 0
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Plan3@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan1@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan1@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan1@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.SelectByID "Base-Révolution@rouleau-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.ClearSelection
Part.ViewZoomTo2 -0.0144452, 0.00833425, -6.86061e-017, -0.00324869, -0.000505106, -6.8812e-018
Part.ViewZoomtofit2
Part.SelectByID "Bague intérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Base-Révolution@rouleau-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.ClearSelection
Part.ViewZoomTo2 -0.0200856, 0.0108598, -8.62418e-017, 0.00121307, -0.00117858, -2.17835e-018
Part.ViewDisplayHiddenremoved
Part.SelectByID "", "FACE", -0.007068221193299, 0.019656351111, -0.002837930789344
Part.ClearSelection
Part.ViewZoomTo2 -0.012995, 0.00503004, -4.55329e-017, -0.00457842, 0.000537571, -1.41622e-017
Part.SelectByID "", "FACE", -0.008214566985514, 0.01938810528554, -0.002783804671125
Part.ViewZoomtofit2
Part.ClearSelection
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.InsertSketch
Part.CreateLine2( 0.01351177573856, -0.002593367633415, 0, 0.004421439587048, -0.002968139749187, 0 ).ConstructionGeometry = TRUE
Part.SetPickMode
Part.ClearSelection
Part.InsertSketch
Part.SelectByID "Esquisse1", "SKETCH", 0, 0, 0
Part.SelectByID "Esquisse1", "SKETCH", 0, 0, 0
Part.EditDelete
Part.SelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.EditPart
Part.ClearSelection
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.InsertSketch
Part.CreateLine2( -0.01344055271252, 0.002535833340055, 0, -0.004508200399955, 0.003114819044304, 0 ).ConstructionGeometry = TRUE
Part.SetPickMode
Part.ClearSelection
Part.SelectByID "Point2", "SKETCHPOINT", -0.004508200399955, 0.003114819044304, 0
Part.SelectByID "", "SILHOUETTE", -0.004929121892428, 0.02110269123807, -0.002946450447315
Part.AndSelectByID "Line1", "SKETCHSEGMENT", -0.002134968278978, 0.006008953222336, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.SelectByID "Point2", "SKETCHPOINT", 0.0005569685575879, 0.003173387225457, 0
Part.ClearSelection
Part.InsertSketch
Part.ClearSelection
Part.EditAssembly
Part.ViewDisplayShaded
Part.SelectByID "Esquisse4@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.SelectByID "Esquisse4@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.BlankSketch
Part.SelectByID "Esquisse4@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.UnblankSketch
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter -0.00439104, -0.21318
Part.ActiveView().RotateAboutCenter -0.00878209, -0.10098
Part.ActiveView().RotateAboutCenter -0.00878209, -0.16269
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0897598
Part.ActiveView().RotateAboutCenter -0.00878209, -0.14586
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0, -0.0224399
Part.ActiveView().RotateAboutCenter -0.0131731, -0.11781
Part.ActiveView().RotateAboutCenter 0, -0.0560999
Part.ActiveView().RotateAboutCenter -0.00439104, -0.01683
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0392699
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0392699
Part.ActiveView().RotateAboutCenter 0, -0.0448799
Part.ActiveView().RotateAboutCenter -0.00439104, -0.12342
Part.ActiveView().RotateAboutCenter 0, -0.0897598
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.0336599
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0560999
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0336599
Part.ActiveView().RotateAboutCenter 0, 0.0392699
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0504899
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0841498
Part.ActiveView().RotateAboutCenter 0.00878209, 0.15147
Part.ActiveView().RotateAboutCenter 0.0307373, 0.314159
Part.ActiveView().RotateAboutCenter 0.00878209, 0.21318
Part.ActiveView().RotateAboutCenter 0, 0.263669
Part.ActiveView().RotateAboutCenter 0, 0.230009
Part.ActiveView().RotateAboutCenter 0, 0.230009
Part.ActiveView().RotateAboutCenter 0, 0.14025
Part.ActiveView().RotateAboutCenter 0, 0.0448799
Part.ActiveView().RotateAboutCenter 0, 0.14025
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0560999
Part.ActiveView().RotateAboutCenter 0.0351284, -0.18513
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.SelectByID "Esquisse4@rouleau-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditDelete
Part.SelectByID "Plan2@rouleau-1@Roulement 20-47", "PLANE", 0, 0, 0
Part.InsertSketch
Part.CreateLine2( 0.01385265753287, -0.003367371939788, 0, 0.002066855743609, -0.003956662029251, 0 ).ConstructionGeometry = TRUE
Part.AndSelectByID "", "SILHOUETTE", -0.00871741532469, 0.01883753733335, -0.002778081850325
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.InsertSketch
Part.ClearSelection
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.SelectByID "Line16", "SKETCHSEGMENT", 0.00301725961149, -0.008291352135115, 0
Part.SelectByID "Line10", "SKETCHSEGMENT", 0.002200003832479, -0.0002995988367809, 0
Part.SelectByID "Ligne1@Esquisse2", "EXTSKETCHSEGMENT", 0.008294276043161, -0.002808472264013, 0
Part.AndSelectByID "Line16", "SKETCHSEGMENT", 0.007272360891187, -0.007676654811482, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, -0.1683
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0729298
Part.ActiveView().RotateAboutCenter -0.00439104, -0.1122
Part.ActiveView().RotateAboutCenter 0, -0.0224399
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter 0.00878209, -0.16269
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0785398
Part.ActiveView().RotateAboutCenter 0, -0.0224399
Part.ActiveView().RotateAboutCenter 0, -0.0392699
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0841498
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.16269
Part.ActiveView().RotateAboutCenter 0, 0.13464
Part.ActiveView().RotateAboutCenter -0.0219552, 0.246839
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0953698
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0897598
Part.ActiveView().RotateAboutCenter -0.00878209, 0.20757
Part.ActiveView().RotateAboutCenter -0.00439104, 0.10098
Part.ActiveView().RotateAboutCenter 0, 0.0785398
Part.ActiveView().RotateAboutCenter 0, 0.0897598
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0617099
Part.InsertSketch
Part.ActiveView().RotateAboutCenter 0.0395194, -0.00560999
Part.ActiveView().RotateAboutCenter 0.144904, -0.0392699
Part.ActiveView().RotateAboutCenter 0.109776, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0614746, 0
Part.ActiveView().RotateAboutCenter 0.0351284, 0
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0131731, 0
Part.ActiveView().RotateAboutCenter -0.0175642, 0
Part.ActiveView().RotateAboutCenter -0.0439104, 0
Part.ActiveView().RotateAboutCenter -0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0570836, -0.15708
Part.ActiveView().RotateAboutCenter 0.0570836, -0.0673198
Part.ActiveView().RotateAboutCenter 0.118558, -0.0224399
Part.ActiveView().RotateAboutCenter 0.0307373, 0
Part.ActiveView().RotateAboutCenter 0.0395194, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0131731, -0.01683
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0224399
Part.ActiveView().RotateAboutCenter 0.0351284, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0504899
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0224399
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter -0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0570836, 0.00560999
Part.ActiveView().RotateAboutCenter -0.096603, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0922119, 0.00560999
Part.ActiveView().RotateAboutCenter -0.096603, 0.0392699
Part.ActiveView().RotateAboutCenter -0.0922119, 0.0673198
Part.ActiveView().RotateAboutCenter -0.0746478, 0.0673198
Part.ActiveView().RotateAboutCenter -0.109776, 0.0560999
Part.ActiveView().RotateAboutCenter -0.0658657, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, 0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.0526925, 0.01122
Part.ActiveView().RotateAboutCenter -0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0175642, 0
Part.ActiveView().RotateAboutCenter -0.0351284, 0
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0131731, 0
Part.ActiveView().RotateAboutCenter 0.0746478, 0.01122
Part.ActiveView().RotateAboutCenter 0.0263463, 0
Part.ActiveView().RotateAboutCenter 0.0570836, 0
Part.ActiveView().RotateAboutCenter 0.0570836, 0
Part.ActiveView().RotateAboutCenter 0.0395194, 0
Part.ActiveView().RotateAboutCenter 0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0263463, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0351284, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0617099
Part.ActiveView().RotateAboutCenter 0.00439104, -0.10098
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0263463, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0448799
Part.ActiveView().RotateAboutCenter 0.0219552, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0, -0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, -0.10098
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0897598
Part.ActiveView().RotateAboutCenter 0.0483015, -0.18513
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0617099
Part.ActiveView().RotateAboutCenter -0.0175642, -0.14025
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.0336599
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0673198
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0785398
Part.ActiveView().RotateAboutCenter 0.0307373, 0.14025
Part.ActiveView().RotateAboutCenter 0.0307373, 0.15147
Part.ActiveView().RotateAboutCenter 0.0878209, 0.258059
Part.ActiveView().RotateAboutCenter 0.0439104, 0.14586
Part.ActiveView().RotateAboutCenter 0.0702567, 0.19635
Part.ActiveView().RotateAboutCenter 0.0263463, 0.11781
Part.ActiveView().RotateAboutCenter 0.0175642, 0.10659
Part.ActiveView().RotateAboutCenter -0.00878209, 0.01683
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0673198
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0392699
Part.ActiveView().RotateAboutCenter -0.0219552, 0.01683
Part.ActiveView().RotateAboutCenter -0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.00878209, -0.01683
Part.ActiveView().RotateAboutCenter -0.0263463, -0.0897598
Part.ActiveView().RotateAboutCenter 0, -0.18513
Part.ActiveView().RotateAboutCenter -0.00439104, -0.19074
Part.ActiveView().RotateAboutCenter -0.0175642, -0.12342
Part.ActiveView().RotateAboutCenter -0.00439104, -0.11781
Part.ActiveView().RotateAboutCenter 0.00439104, -0.17391
Part.ActiveView().RotateAboutCenter 0, -0.0560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.12903
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0336599
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0224399
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0280499
Part.ActiveView().RotateAboutCenter 0.00878209, 0.21318
Part.ActiveView().RotateAboutCenter -0.00878209, 0.319769
Part.ActiveView().RotateAboutCenter -0.0219552, 0.274889
Part.ActiveView().RotateAboutCenter -0.00878209, 0.297329
Part.ActiveView().RotateAboutCenter 0, 0.1122
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0897598
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0746478, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0614746, 0.0392699
Part.ActiveView().RotateAboutCenter -0.0746478, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0395194, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, 0.01122
Part.ActiveView().RotateAboutCenter -0.0483015, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0351284, 0.01683
Part.ActiveView().RotateAboutCenter -0.0263463, 0.01122
Part.ActiveView().RotateAboutCenter -0.0175642, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.10098
Part.ActiveView().RotateAboutCenter 0, -0.0617099
Part.ActiveView().RotateAboutCenter 0, -0.10659
Part.ActiveView().RotateAboutCenter 0, -0.0953698
Part.ActiveView().RotateAboutCenter 0.00439104, -0.10098
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0729298
Part.ActiveView().RotateAboutCenter 0, -0.11781
Part.ActiveView().RotateAboutCenter 0, -0.0673198
Part.ActiveView().RotateAboutCenter -0.00439104, -0.14586
Part.ActiveView().RotateAboutCenter 0, -0.10659
Part.ActiveView().RotateAboutCenter 0, -0.10098
Part.ActiveView().RotateAboutCenter 0, -0.11781
Part.ActiveView().RotateAboutCenter 0.00878209, -0.10098
Part.ActiveView().RotateAboutCenter 0.00878209, -0.11781
Part.ActiveView().RotateAboutCenter 0, -0.0841498
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0841498
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0953698
Part.ActiveView().RotateAboutCenter -0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter -0.0307373, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0351284, -0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0878209, -0.0280499
Part.ActiveView().RotateAboutCenter -0.0746478, -0.01683
Part.ActiveView().RotateAboutCenter -0.0307373, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0673198
Part.ActiveView().RotateAboutCenter 0.0175642, -0.12903
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0841498
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0392699
Part.ActiveView().RotateAboutCenter 0.0307373, 0
Part.ActiveView().RotateAboutCenter 0.0526925, 0.0953698
Part.ActiveView().RotateAboutCenter 0.0614746, 0.230009
Part.ActiveView().RotateAboutCenter 0.0614746, 0.11781
Part.ActiveView().RotateAboutCenter 0.0834298, 0.14025
Part.ActiveView().RotateAboutCenter 0.0175642, 0.0280499
Part.ActiveView().RotateAboutCenter 0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter 0.118558, 0.314159
Part.ActiveView().RotateAboutCenter 0.0746478, 0.302939
Part.ActiveView().RotateAboutCenter 0.0878209, 0.381479
Part.ActiveView().RotateAboutCenter 0.0131731, 0.17952
Part.ActiveView().RotateAboutCenter -0.0131731, 0.11781
Part.ActiveView().RotateAboutCenter -0.0746478, 0.13464
Part.ActiveView().RotateAboutCenter -0.0526925, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0395194, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, 0
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.0224399
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.00439104, -0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0790388, 0.01122
Part.ActiveView().RotateAboutCenter -0.0834298, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0483015, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0175642, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.0131731, -0.01122
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.ViewZoomtofit2
Part.SelectByID "D2@Esquisse4@Cage-1@Roulement 20-47", "DIMENSION", -0.02555348954404, 0.008020367130316, -0.0181664924805
Part.Parameter("D2@Esquisse4@Cage.Part").SystemValue = 0.0005
Part.SelectByID "D2@Esquisse4@Cage-1@Roulement 20-47", "DIMENSION", -0.02548616050705, 0.007873515706352, -0.0177413726677
Part.EditDelete
Part.SelectByID "Line10", "SKETCHSEGMENT", 0.002601711235053, -0.001264194491787, 0
Part.ClearSelection
Part.EditUndo 1
Part.SelectByID "D2@Esquisse4@Cage-1@Roulement 20-47", "DIMENSION", -0.0263931156986, 0.008289230706118, -0.01881635984408
Part.Parameter("D2@Esquisse4@Cage.Part").SystemValue = 0.001
Part.ClearSelection
Part.InsertSketch
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, -0.16269
Part.ActiveView().RotateAboutCenter -0.0131731, -0.16269
Part.ActiveView().RotateAboutCenter -0.0175642, -0.0392699
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.0841498
Part.ActiveView().RotateAboutCenter -0.0219552, -0.0673198
Part.ActiveView().RotateAboutCenter -0.0263463, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0483015, -0.01683
Part.ActiveView().RotateAboutCenter -0.0395194, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0351284, -0.01122
Part.ActiveView().RotateAboutCenter -0.0614746, -0.01683
Part.ActiveView().RotateAboutCenter -0.0351284, -0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0
Part.ActiveView().RotateAboutCenter -0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0617099
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0175642, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0614746, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0702567, -0.01122
Part.ActiveView().RotateAboutCenter 0.114167, -0.0785398
Part.ActiveView().RotateAboutCenter 0.100994, -0.0841498
Part.ActiveView().RotateAboutCenter 0.0834298, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter 0.0351284, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0280499
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0224399
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.01683
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0953698
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0483015, 0.1122
Part.ActiveView().RotateAboutCenter -0.100994, 0.235619
Part.ActiveView().RotateAboutCenter -0.0834298, 0.19635
Part.ActiveView().RotateAboutCenter -0.0702567, 0.15147
Part.ActiveView().RotateAboutCenter -0.0483015, 0.10659
Part.ActiveView().RotateAboutCenter -0.0219552, 0.10659
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0.109776, 0.01122
Part.ActiveView().RotateAboutCenter 0.0395194, 0
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.SelectByID "D2@Esquisse4@Cage-1@Roulement 20-47", "DIMENSION", -0.02474131489875, 0.01195857533547, -0.01803430825227
Part.Parameter("D2@Esquisse4@Cage.Part").SystemValue = 0.0008
Part.ClearSelection
Part.InsertSketch
Part.ActiveView().RotateAboutCenter -0.0175642, 0
Part.ActiveView().RotateAboutCenter -0.140513, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0395194, 0.01683
Part.ActiveView().RotateAboutCenter -0.0439104, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0351284, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0175642, 0.01122
Part.ActiveView().RotateAboutCenter -0.0351284, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0263463, 0.01683
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0483015, -0.0392699
Part.ActiveView().RotateAboutCenter 0.0790388, -0.0729298
Part.ActiveView().RotateAboutCenter 0.0526925, -0.0785398
Part.ActiveView().RotateAboutCenter 0.0307373, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0673198
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0504899
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0729298
Part.ActiveView().RotateAboutCenter 0, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0560999
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0729298
Part.ActiveView().RotateAboutCenter 0.0351284, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0392699
Part.ActiveView().RotateAboutCenter 0.0131731, -0.01683
Part.ActiveView().RotateAboutCenter 0.0307373, -0.1122
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0448799
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0614746, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0658657, 0.01683
Part.ActiveView().RotateAboutCenter -0.109776, 0.0785398
Part.ActiveView().RotateAboutCenter -0.0746478, 0.0953698
Part.ActiveView().RotateAboutCenter -0.105385, 0.19635
Part.ActiveView().RotateAboutCenter -0.100994, 0.342209
Part.ActiveView().RotateAboutCenter -0.0483015, 0.235619
Part.ActiveView().RotateAboutCenter -0.0614746, 0.370259
Part.ActiveView().RotateAboutCenter -0.0263463, 0.246839
Part.ActiveView().RotateAboutCenter 0, 0.11781
Part.ActiveView().RotateAboutCenter 0, 0.15708
Part.ActiveView().RotateAboutCenter -0.00439104, 0.10098
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0175642, 0.01122
Part.ActiveView().RotateAboutCenter -0.109776, -0.13464
Part.ActiveView().RotateAboutCenter -0.122949, -0.504899
Part.ActiveView().RotateAboutCenter -0.0219552, -0.336599
Part.ActiveView().RotateAboutCenter -0.00878209, -0.17952
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0746478, -0.0336599
Part.ActiveView().RotateAboutCenter -0.105385, 0.01122
Part.ActiveView().RotateAboutCenter -0.0395194, 0.0560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0785398
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0224399
Part.EditAssembly
Part.SelectByID "Bague extérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Base-Révolution@Bague extérieure-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.SelectByID "Line1", "SKETCHSEGMENT", -0.01089678156961, 0.026, 0
Part.SketchConstraintsDel 4, "sgDISTANCE"
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Base-Révolution@Bague extérieure-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 30205.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.SketchConstraintsDel 0, "sgCOINCIDENT"
Part.SketchConstraintsDel 0, "sgCOLINEAR"
Part.SketchConstraintsDel 0, "sgATMIDDLE"
Part.SketchConstraintsDel 1, "sgCOINCIDENT"
Part.SketchConstraintsDel 1, "sgPERPENDICULAR"
Part.SelectByID "Line1", "SKETCHSEGMENT", -0.00949019866552, 0.026, 0
Part.SelectByID "Line3", "SKETCHSEGMENT", -0.009252089809063, 0.02156505743535, 0
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Bague intérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Répétition circulaire locale1", "COMPPATTERN", 0, 0, 0
Part.ClearSelection
Part.AndSelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.AndSelectByID "@Bague intérieure-1@Roulement 20-47", "AXIS", 0, 0, 0
Part.ClearSelection
Part.ClearSelection
Part.SelectByID "Esquisse1@Bague extérieure-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.SelectByID "Line3", "SKETCHSEGMENT", -0.009050418444199, 0.02430551859751, 0
Part.AndSelectByID "", "SILHOUETTE", -0.007827873415237, 0.02216413042915, 0
Part.SketchAddConstraints "sgCOLINEAR"
Part.ClearSelection
Part.SelectByID "Point10", "SKETCHPOINT", -0.007918228917682, 0.01638484537696, 0
Part.AndSelectByID "", "SILHOUETTE", -0.004886836433965, 0.01653779881281, 0
Part.SketchAddConstraints "sgATMIDDLE"
Part.ClearSelection
Part.AndSelectByID "Point14", "SKETCHPOINT", -0.002692111917327, -0.002427439890687, 0
Part.AndSelectByID "Line5", "SKETCHSEGMENT", -0.009745941011718, 0, 0
Part.SketchAddConstraints "sgCOINCIDENT"
Part.ClearSelection
Part.AndSelectByID "Line5", "SKETCHSEGMENT", -0.007700002242138, -0.002427439890687, 0
Part.AndSelectByID "Point1@Origine", "EXTSKETCHPOINT", 0, 0, 0
Part.SketchAddConstraints "sgCOINCIDENT"
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.AndSelectByID "@rouleau-1@Roulement 20-47", "AXIS", 0.0006116240092807, 0.02101328987127, 0
Part.AndSelectByID "Line8", "SKETCHSEGMENT", -0.005991674949004, 0.01003149998614, 0
Part.SketchAddConstraints "sgPERPENDICULAR"
Part.ClearSelection
Part.SelectByID "Line5", "SKETCHSEGMENT", -0.007700002242138, 0, 0
Part.AndSelectByID "Line1", "SKETCHSEGMENT", -0.005781934645657, 0.02728108975129, 0
Part.AddDimension 0.0157004, 0.0156427, 0
Part.ClearSelection
Part.Parameter("D2@Esquisse1@Bague extérieure.Part").SystemValue = 0.026
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.SelectByID "Dans fonction de contexte5", "INCONTEXTFEATS", 0, 0, 0
Part.ReorderFeature "Dans fonction de contexte5", "Dans fonction de contexte3"
Part.ClearSelection
Part.SelectByID "Répétition circulaire locale1", "COMPPATTERN", 0, 0, 0
Part.ClearSelection
Part.AndSelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.AndSelectByID "@Bague intérieure-1@Roulement 20-47", "AXIS", 0, 0, 0
Part.ClearSelection
Part.ClearSelection
Part.ViewDispTempRefaxes
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0785398
Part.ActiveView().RotateAboutCenter -0.0131731, -0.330989
Part.ActiveView().RotateAboutCenter -0.0175642, -0.20196
Part.ActiveView().RotateAboutCenter -0.0439104, -0.241229
Part.ActiveView().RotateAboutCenter -0.0702567, -0.336599
Part.ActiveView().RotateAboutCenter -0.00439104, -0.224399
Part.ActiveView().RotateAboutCenter -0.0131731, -0.14025
Part.ActiveView().RotateAboutCenter -0.0131731, -0.0617099
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0.0307373, -0.0560999
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0224399
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0504899
Part.ActiveView().RotateAboutCenter 0.0175642, 0.224399
Part.ActiveView().RotateAboutCenter 0.0131731, 0.10098
Part.ActiveView().RotateAboutCenter 0.0219552, 0.0560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0504899
Part.ActiveView().RotateAboutCenter -0.0483015, 0.269279
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0841498
Part.ActiveView().RotateAboutCenter 0.00878209, 0.01683
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.SelectByID "Cage-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Bague intérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0439104, 0.706858
Part.ActiveView().RotateAboutCenter -0.0351284, 0.392699
Part.ActiveView().RotateAboutCenter -0.0483015, 0.252449
Part.ActiveView().RotateAboutCenter -0.100994, 0.403919
Part.ActiveView().RotateAboutCenter -0.0790388, 0.15147
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0175642, -0.18513
Part.ActiveView().RotateAboutCenter 0, -0.12342
Part.ActiveView().RotateAboutCenter -0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0785398
Part.ActiveView().RotateAboutCenter 0.0263463, -0.19635
Part.ActiveView().RotateAboutCenter 0.0439104, -0.269279
Part.ActiveView().RotateAboutCenter 0.0395194, -0.370259
Part.ActiveView().RotateAboutCenter 0.0175642, -0.336599
Part.ActiveView().RotateAboutCenter -0.0351284, -0.330989
Part.ActiveView().RotateAboutCenter -0.0878209, -0.20757
Part.ActiveView().RotateAboutCenter -0.0702567, -0.0280499
Part.ActiveView().RotateAboutCenter -0.114167, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0395194, -0.01683
Part.ActiveView().RotateAboutCenter 0, 0
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Set Part = swApp.OpenDoc ("C:\Jean-Marie\TP\Suspension\Etude mécanique\Boîte de vitesses\Arbre d'entrée\Roulement conique d25\Roulement 30205.SLDASM", 2)
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 30205")
Part.SelectByID "Bague extérieure-1@Roulement 30205", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Bague intérieure-1@Roulement 30205", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Cage-1@Roulement 30205", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Bague intérieure-1@Roulement 30205", "COMPONENT", 0, 0, 0
Part.SelectByID "Esquisse1@Bague extérieure-1@Roulement 30205", "SKETCH", 0, 0, 0
Part.EditSketch
' MSGBOX
' Cette pièce a des fonctions définies dans le contexte d'un autre assemblage <Roulement 20-47.sldasm>. Vous pouvez éditer la pièce, mais vous ne pouvez pas créer de références externes aux composants de l'assemblage actuel.

Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.EditRebuild
Set Part = Nothing
swApp.CloseDoc "Roulement 30205"
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Roulement 20-47")
Part.SelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.EditPart
Part.ClearSelection
Part.EditAssembly
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0834298, 0.19635
Part.ActiveView().RotateAboutCenter -0.12734, 0.17391
Part.ActiveView().RotateAboutCenter -0.140513, 0.20757
Part.ActiveView().RotateAboutCenter -0.105385, 0.17952
Part.ActiveView().RotateAboutCenter -0.175642, 0.16269
Part.ActiveView().RotateAboutCenter -0.201988, 0.14025
Part.ActiveView().RotateAboutCenter -0.0395194, 0.12903
Part.ActiveView().RotateAboutCenter 0.0526925, 0.12903
Part.ActiveView().RotateAboutCenter 0.25029, 0.12903
Part.ActiveView().RotateAboutCenter 0.259072, 0.0673198
Part.ActiveView().RotateAboutCenter 0.237116, -0.0560999
Part.ActiveView().RotateAboutCenter 0.100994, -0.443189
Part.ActiveView().RotateAboutCenter 0.0658657, -0.617099
Part.ActiveView().RotateAboutCenter 0.0922119, -0.762958
Part.ActiveView().RotateAboutCenter 0.12734, -0.729298
Part.ActiveView().RotateAboutCenter 0.136122, -0.15147
Part.ActiveView().RotateAboutCenter 0.153687, 0.0953698
Part.ActiveView().RotateAboutCenter 0.188815, 0.258059
Part.ActiveView().RotateAboutCenter 0.140513, 0.387089
Part.ActiveView().RotateAboutCenter 0.0834298, 0.241229
Part.ActiveView().RotateAboutCenter 0.0219552, 0.15708
Part.ActiveView().RotateAboutCenter 0.0395194, 0.19074
Part.ActiveView().RotateAboutCenter 0.00878209, 0.269279
Part.ActiveView().RotateAboutCenter -0.0526925, 0.14025
Part.ActiveView().RotateAboutCenter -0.100994, 0.20196
Part.ActiveView().RotateAboutCenter -0.0351284, 0.0729298
Part.ActiveView().RotateAboutCenter -0.0658657, -0.11781
Part.ActiveView().RotateAboutCenter -0.149296, -0.20196
Part.ActiveView().RotateAboutCenter -0.171251, -0.274889
Part.ActiveView().RotateAboutCenter -0.0878209, -0.0729298
Part.ActiveView().RotateAboutCenter -0.12734, -0.0336599
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0790388, -0.01683
Part.ActiveView().RotateAboutCenter 0.158078, -0.00560999
Part.ActiveView().RotateAboutCenter 0.140513, 0.0841498
Part.ActiveView().RotateAboutCenter 0.0395194, 0.0729298
Part.ActiveView().RotateAboutCenter 0.0131731, 0.0336599
Part.SelectByID "Bague intérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.EditPart
Part.ClearSelection
Part.SelectByID "Base-Révolution@Bague intérieure-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
Part.ClearSelection
Part.SelectByID "D2@Esquisse1@Bague intérieure-1@Roulement 20-47", "DIMENSION", -0.02293341254486, -0.01953679192895, 0
Part.Parameter("D2@Esquisse1@Bague intérieure.Part").SystemValue = 0.01
Part.SelectByID "D3@Esquisse1@Bague intérieure-1@Roulement 20-47", "DIMENSION", 0.03709495058237, 0.008485297937968, 0
Part.Parameter("D3@Esquisse1@Bague intérieure.Part").SystemValue = 0.018
Part.ClearSelection
Part.InsertSketch
Part.ActiveView().RotateAboutCenter 0.0219552, -0.319769
Part.ActiveView().RotateAboutCenter 0, -0.16269
Part.ActiveView().RotateAboutCenter 0.00439104, -0.16269
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0897598
Part.ActiveView().RotateAboutCenter 0.0351284, -0.10098
Part.ActiveView().RotateAboutCenter 0, -0.0953698
Part.ActiveView().RotateAboutCenter -0.00439104, -0.15708
Part.ActiveView().RotateAboutCenter -0.0175642, -0.15708
Part.ActiveView().RotateAboutCenter -0.0483015, -0.12342
Part.ActiveView().RotateAboutCenter -0.0175642, -0.0617099
Part.ActiveView().RotateAboutCenter -0.00439104, -0.10098
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0617099
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0336599
Part.ActiveView().RotateAboutCenter 0, 0.0280499
Part.ActiveView().RotateAboutCenter 0, 0.0280499
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.0448799
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.0280499
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0729298
Part.ActiveView().RotateAboutCenter 0, 0.10098
Part.ActiveView().RotateAboutCenter 0, 0.0560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0953698
Part.ActiveView().RotateAboutCenter -0.00439104, 0.10098
Part.ActiveView().RotateAboutCenter 0, 0.12342
Part.ActiveView().RotateAboutCenter -0.00439104, 0.12903
Part.ActiveView().RotateAboutCenter 0, 0.14586
Part.ActiveView().RotateAboutCenter 0, 0.19635
Part.ActiveView().RotateAboutCenter 0, 0.19635
Part.ActiveView().RotateAboutCenter 0.00878209, 0.274889
Part.ActiveView().RotateAboutCenter 0, 0.18513
Part.ActiveView().RotateAboutCenter -0.0175642, 0.17391
Part.ActiveView().RotateAboutCenter -0.0702567, 0.274889
Part.ActiveView().RotateAboutCenter -0.0307373, 0.1683
Part.ActiveView().RotateAboutCenter -0.0658657, 0.1683
Part.ActiveView().RotateAboutCenter -0.0702567, 0.19074
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0673198
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0.0395194, -0.0673198
Part.ActiveView().RotateAboutCenter 0.0790388, -0.15147
Part.ActiveView().RotateAboutCenter 0.0614746, -0.11781
Part.ActiveView().RotateAboutCenter 0.0307373, -0.0729298
Part.ActiveView().RotateAboutCenter 0.0351284, -0.10659
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0897598
Part.ActiveView().RotateAboutCenter 0.0526925, -0.20196
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0841498
Part.ActiveView().RotateAboutCenter 0.0263463, -0.409529
Part.ActiveView().RotateAboutCenter 0.00439104, -0.19074
Part.ActiveView().RotateAboutCenter 0.00439104, -0.230009
Part.ActiveView().RotateAboutCenter 0.00878209, -0.21318
Part.ActiveView().RotateAboutCenter 0, -0.0224399
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0841498
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0280499
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.0448799
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0392699
Part.ActiveView().RotateAboutCenter 0.0131731, 0.0785398
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.EditAssembly
Part.SelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.EditPart
Part.ClearSelection
Part.SelectByID "Base-Révolution@rouleau-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
Part.ClearSelection
Part.SelectByID "D3@Esquisse1@rouleau-1@Roulement 20-47", "DIMENSION", 0.002050297974092, 0.02733666742823, 0
Part.Parameter("D3@Esquisse1@rouleau.Part").SystemValue = 0.0035
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0131731, -0.218789
Part.ActiveView().RotateAboutCenter 0.0131731, -0.246839
Part.ActiveView().RotateAboutCenter 0.0307373, -0.235619
Part.ActiveView().RotateAboutCenter 0.00878209, -0.230009
Part.ActiveView().RotateAboutCenter 0.00439104, -0.269279
Part.ActiveView().RotateAboutCenter -0.0526925, -0.235619
Part.ActiveView().RotateAboutCenter -0.0131731, -0.1122
Part.ActiveView().RotateAboutCenter 0, -0.0729298
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0729298
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0280499
Part.ActiveView().RotateAboutCenter 0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0504899
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0392699
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01683
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0617099
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0785398
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0897598
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0785398
Part.ActiveView().RotateAboutCenter -0.0307373, 0.10659
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0673198
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0175642, -0.10098
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0897598
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0504899
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0504899
Part.ActiveView().RotateAboutCenter 0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0219552, 0.0504899
Part.ActiveView().RotateAboutCenter 0.0175642, 0.241229
Part.ActiveView().RotateAboutCenter 0.0263463, 0.14025
Part.ActiveView().RotateAboutCenter 0.0175642, 0.263669
Part.ActiveView().RotateAboutCenter 0, 0.15147
Part.ActiveView().RotateAboutCenter -0.00878209, 0.14025
Part.ActiveView().RotateAboutCenter 0, 0.15708
Part.ActiveView().RotateAboutCenter -0.00439104, 0.10659
Part.ActiveView().RotateAboutCenter -0.0175642, 0.0841498
Part.ActiveView().RotateAboutCenter -0.00878209, 0.10098
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter 0.0175642, -0.12342
Part.ActiveView().RotateAboutCenter 0.0219552, -0.224399
Part.ActiveView().RotateAboutCenter 0.0263463, -0.409529
Part.ActiveView().RotateAboutCenter 0.00878209, -0.375869
Part.ActiveView().RotateAboutCenter 0, -0.302939
Part.ActiveView().RotateAboutCenter 0, -0.0841498
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0673198
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0336599
Part.ActiveView().RotateAboutCenter 0, 0.01683
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0504899
Part.ActiveView().RotateAboutCenter 0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter 0.00439104, 0.1122
Part.ActiveView().RotateAboutCenter 0.00439104, 0.1683
Part.ActiveView().RotateAboutCenter -0.0175642, 0.21318
Part.ActiveView().RotateAboutCenter 0, 0.15708
Part.ActiveView().RotateAboutCenter 0, 0.308549
Part.ActiveView().RotateAboutCenter -0.00439104, 0.21318
Part.ActiveView().RotateAboutCenter 0, 0.12342
Part.ActiveView().RotateAboutCenter 0.00439104, 0.1122
Part.ActiveView().RotateAboutCenter 0, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0504899
Part.ActiveView().RotateAboutCenter -0.0175642, 0.0336599
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.SelectByID "Base-Révolution@Bague extérieure-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
Part.ClearSelection
Part.SelectByID "D2@Esquisse1@Bague extérieure-1@Roulement 20-47", "DIMENSION", 0.01214382954422, 0.01445905006512, 0
Part.Parameter("D2@Esquisse1@Bague extérieure.Part").SystemValue = 0.0235
Part.SelectByID "D2@Esquisse1@Bague extérieure-1@Roulement 20-47", "DIMENSION", 0.01341748302232, 0.01191174310893, 0
Part.Parameter("D2@Esquisse1@Bague extérieure.Part").SystemValue = 0.025
Part.SelectByID "D2@Esquisse1@Bague extérieure-1@Roulement 20-47", "DIMENSION", 0.01252592558765, 0.01344012728264, 0
Part.Parameter("D2@Esquisse1@Bague extérieure.Part").SystemValue = 0.026
Part.ClearSelection
Part.InsertSketch
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0351284, -0.252449
Part.ActiveView().RotateAboutCenter -0.00439104, -0.224399
Part.ActiveView().RotateAboutCenter -0.00439104, -0.19074
Part.ActiveView().RotateAboutCenter 0.00439104, -0.12903
Part.ActiveView().RotateAboutCenter 0.00878209, -0.218789
Part.ActiveView().RotateAboutCenter -0.00439104, -0.15708
Part.ActiveView().RotateAboutCenter 0.0570836, -0.21318
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0560999
Part.ActiveView().RotateAboutCenter 0.109776, -0.18513
Part.ActiveView().RotateAboutCenter 0.0614746, -0.13464
Part.ActiveView().RotateAboutCenter -0.0131731, -0.0448799
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0448799
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0395194, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0439104, 0.11781
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0483015, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0483015, 0
Part.ActiveView().RotateAboutCenter -0.0483015, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0439104, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0224399
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.EditAssembly
Part.SelectByID "Répétition circulaire locale1", "COMPPATTERN", 0, 0, 0
Part.ClearSelection
Part.AndSelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.AndSelectByID "@Bague intérieure-1@Roulement 20-47", "AXIS", 0, 0, 0
Part.ClearSelection
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0307373, -0.00560999
Part.ActiveView().RotateAboutCenter 0.105385, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0526925, -0.01683
Part.ActiveView().RotateAboutCenter 0.0263463, 0
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.0224399
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0, -0.0336599
Part.SelectByID "rouleau-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.SelectByID "Base-Révolution@rouleau-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.FeatEdit
Part.ClearSelection
Part.SelectByID "D3@Esquisse1@rouleau-1@Roulement 20-47", "DIMENSION", 0.001764171980102, 0.02618449840415, 0
Part.Parameter("D3@Esquisse1@rouleau.Part").SystemValue = 0.004
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0351284, -0.15708
Part.ActiveView().RotateAboutCenter 0.0131731, -0.12342
Part.ActiveView().RotateAboutCenter 0.00878209, -0.252449
Part.ActiveView().RotateAboutCenter 0, -0.280499
Part.ActiveView().RotateAboutCenter 0.0263463, -0.21318
Part.ActiveView().RotateAboutCenter 0.00878209, -0.12903
Part.ActiveView().RotateAboutCenter 0, -0.15147
Part.ActiveView().RotateAboutCenter 0, -0.18513
Part.ActiveView().RotateAboutCenter 0.00878209, -0.1683
Part.ActiveView().RotateAboutCenter 0.0307373, -0.15708
Part.ActiveView().RotateAboutCenter 0.00439104, -0.13464
Part.ActiveView().RotateAboutCenter -0.0614746, 0.0729298
Part.ActiveView().RotateAboutCenter -0.105385, 0.0504899
Part.ActiveView().RotateAboutCenter -0.0570836, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0673198
Part.ActiveView().RotateAboutCenter 0.0439104, 0.0336599
Part.ActiveView().RotateAboutCenter 0.0307373, 0.01683
Part.ActiveView().RotateAboutCenter 0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0175642, -0.01122
Part.ActiveView().RotateAboutCenter 0.0307373, -0.0224399
Part.ActiveView().RotateAboutCenter -0.00878209, -0.0224399
Part.ActiveView().RotateAboutCenter -0.0219552, -0.0504899
Part.ActiveView().RotateAboutCenter -0.00878209, -0.01683
Part.ActiveView().RotateAboutCenter -0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter -0.0439104, -0.0897598
Part.ActiveView().RotateAboutCenter -0.0307373, -0.10098
Part.ActiveView().RotateAboutCenter -0.0702567, -0.0504899
Part.ActiveView().RotateAboutCenter -0.0570836, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0351284, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0263463, -0.0673198
Part.ActiveView().RotateAboutCenter -0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0729298
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0841498
Part.ActiveView().RotateAboutCenter 0.0834298, -0.15147
Part.ActiveView().RotateAboutCenter 0.0307373, -0.0448799
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0175642, 0.10659
Part.ActiveView().RotateAboutCenter -0.00878209, 0.19635
Part.ActiveView().RotateAboutCenter 0, 0.0617099
Part.ActiveView().RotateAboutCenter -0.0219552, 0.15147
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0897598
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0841498
Part.ActiveView().RotateAboutCenter 0.0483015, 0.13464
Part.ActiveView().RotateAboutCenter 0.0790388, 0.12342
Part.ActiveView().RotateAboutCenter 0.0614746, 0.0897598
Part.ActiveView().RotateAboutCenter 0.0922119, 0.12342
Part.ActiveView().RotateAboutCenter 0.100994, 0.13464
Part.ActiveView().RotateAboutCenter 0.0395194, 0.0673198
Part.ActiveView().RotateAboutCenter 0.0175642, 0.0336599
Part.ActiveView().RotateAboutCenter 0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0448799
Part.ActiveView().RotateAboutCenter 0.00878209, 0.13464
Part.ActiveView().RotateAboutCenter 0, 0.0560999
Part.ActiveView().RotateAboutCenter 0, 0.14025
Part.ActiveView().RotateAboutCenter 0, 0.0617099
Part.ActiveView().RotateAboutCenter 0.00439104, 0.14025
Part.ActiveView().RotateAboutCenter 0, 0.01683
Part.ActiveView().RotateAboutCenter 0.0131731, 0.13464
Part.ActiveView().RotateAboutCenter -0.00439104, 0.14025
Part.ActiveView().RotateAboutCenter -0.0175642, 0.10098
Part.ActiveView().RotateAboutCenter -0.0351284, 0.0560999
Part.ActiveView().RotateAboutCenter -0.0570836, 0.0392699
Part.ActiveView().RotateAboutCenter -0.0702567, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0570836, 0.01122
Part.ActiveView().RotateAboutCenter -0.0614746, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0263463, 0.10659
Part.ActiveView().RotateAboutCenter 0, 0.18513
Part.ActiveView().RotateAboutCenter -0.00878209, 0.16269
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0790388, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0878209, -0.0560999
Part.ActiveView().RotateAboutCenter -0.0922119, -0.10659
Part.ActiveView().RotateAboutCenter -0.0746478, -0.0729298
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0280499
Part.ActiveView().RotateAboutCenter -0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0392699
Part.SelectByID "Bague extérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, -0.10659
Part.ActiveView().RotateAboutCenter -0.0483015, -0.0953698
Part.ActiveView().RotateAboutCenter -0.0790388, -0.17391
Part.ActiveView().RotateAboutCenter -0.0219552, -0.11781
Part.ActiveView().RotateAboutCenter -0.00878209, -0.1122
Part.ActiveView().RotateAboutCenter 0, -0.0953698
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.10659
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0617099
Part.ActiveView().RotateAboutCenter -0.0219552, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0219552, -0.0841498
Part.ActiveView().RotateAboutCenter -0.0131731, -0.0392699
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0897598
Part.ActiveView().RotateAboutCenter -0.0131731, -0.0280499
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.0336599
Part.ActiveView().RotateAboutCenter -0.00439104, -0.0673198
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0448799
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0131731, 0.10098
Part.ActiveView().RotateAboutCenter -0.0263463, 0.10659
Part.ActiveView().RotateAboutCenter -0.0702567, 0.20196
Part.ActiveView().RotateAboutCenter -0.0702567, 0.263669
Part.ActiveView().RotateAboutCenter -0.0878209, 0.342209
Part.ActiveView().RotateAboutCenter -0.0351284, 0.17952
Part.ActiveView().RotateAboutCenter -0.0439104, 0.235619
Part.ActiveView().RotateAboutCenter -0.0131731, 0.16269
Part.ActiveView().RotateAboutCenter -0.0175642, 0.12342
Part.ActiveView().RotateAboutCenter -0.0307373, 0.1122
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter 0.105385, -0.0560999
Part.ActiveView().RotateAboutCenter 0.184424, -0.0729298
Part.ActiveView().RotateAboutCenter 0.096603, -0.01122
Part.ActiveView().RotateAboutCenter 0.0526925, 0
Part.ActiveView().RotateAboutCenter 0.0307373, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0307373, 0
Part.ActiveView().RotateAboutCenter 0.0790388, 0
Part.ActiveView().RotateAboutCenter 0.0526925, 0
Part.ActiveView().RotateAboutCenter 0.0351284, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ActiveView().RotateAboutCenter 0.0263463, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0131731, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ActiveView().RotateAboutCenter 0.0175642, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0439104, 0
Part.ActiveView().RotateAboutCenter -0.0307373, 0
Part.ActiveView().RotateAboutCenter -0.0263463, 0
Part.ActiveView().RotateAboutCenter -0.0131731, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0307373, 0
Part.ActiveView().RotateAboutCenter -0.0483015, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0526925, -0.01122
Part.ActiveView().RotateAboutCenter -0.0746478, -0.0336599
Part.ActiveView().RotateAboutCenter -0.096603, -0.0785398
Part.ActiveView().RotateAboutCenter -0.0263463, -0.0224399
Part.ActiveView().RotateAboutCenter -0.0351284, -0.01122
Part.ActiveView().RotateAboutCenter -0.0351284, -0.01683
Part.ActiveView().RotateAboutCenter -0.0263463, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0219552, 0
Part.ActiveView().RotateAboutCenter -0.0175642, 0
Part.ActiveView().RotateAboutCenter -0.0219552, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0351284, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.0922119, 0.01122
Part.ActiveView().RotateAboutCenter 0.0790388, 0.01683
Part.ActiveView().RotateAboutCenter 0.114167, 0.0280499
Part.ActiveView().RotateAboutCenter 0.0658657, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0219552, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0395194, 0
Part.ActiveView().RotateAboutCenter 0.0263463, 0
Part.ActiveView().RotateAboutCenter 0.0570836, 0.00560999
Part.ActiveView().RotateAboutCenter 0.096603, 0.01122
Part.ActiveView().RotateAboutCenter 0.0614746, 0.01122
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.188815, -0.0336599
Part.ActiveView().RotateAboutCenter 0.114167, -0.01122
Part.ActiveView().RotateAboutCenter 0.118558, 0
Part.ActiveView().RotateAboutCenter 0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0483015, 0.01122
Part.ActiveView().RotateAboutCenter 0.0526925, 0.01122
Part.ActiveView().RotateAboutCenter 0.0219552, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter 0.16686, -0.0841498
Part.ActiveView().RotateAboutCenter 0.162469, -0.0280499
Part.ActiveView().RotateAboutCenter 0.136122, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0834298, 0.01122
Part.ActiveView().RotateAboutCenter 0.096603, 0.0448799
Part.ActiveView().RotateAboutCenter 0.0922119, 0.1122
Part.ActiveView().RotateAboutCenter 0.0395194, 0.0224399
Part.ActiveView().RotateAboutCenter 0.0395194, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0351284, 0.01122
Part.ActiveView().RotateAboutCenter 0.0483015, 0
Part.ActiveView().RotateAboutCenter 0.0395194, 0
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0219552, -0.01122
Part.ActiveView().RotateAboutCenter 0.193206, -0.0560999
Part.ActiveView().RotateAboutCenter 0.162469, -0.0392699
Part.ActiveView().RotateAboutCenter 0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.SelectByID "Répétition circulaire1@Cage-1@Roulement 20-47", "BODYFEATURE", 0, 0, 0
Part.ClearSelection
Part.AndSelectByID "@Cage-1@Roulement 20-47", "AXIS", -0.003385649603644, 0, 0
Part.ActivateSelectedFeature
Part.ActiveView().RotateAboutCenter 0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0922119, 0.12903
Part.ActiveView().RotateAboutCenter 0.0175642, 0.0448799
Part.ActiveView().RotateAboutCenter 0.0307373, 0.0729298
Part.ActiveView().RotateAboutCenter 0.0570836, 0.10098
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter 0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0392699
Part.ActiveView().RotateAboutCenter 0, -0.17391
Part.ActiveView().RotateAboutCenter 0.0175642, -0.1683
Part.ActiveView().RotateAboutCenter 0.0570836, -0.20196
Part.ActiveView().RotateAboutCenter 0.0307373, -0.17952
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0953698
Part.ActiveView().RotateAboutCenter 0, -0.252449
Part.ActiveView().RotateAboutCenter 0, -0.10098
Part.ActiveView().RotateAboutCenter 0, -0.0504899
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.ActiveView().RotateAboutCenter 0, 0.280499
Part.ActiveView().RotateAboutCenter 0.0131731, 0.20757
Part.ActiveView().RotateAboutCenter 0.0658657, 0.241229
Part.ActiveView().RotateAboutCenter 0.0439104, 0.15147
Part.ActiveView().RotateAboutCenter 0.0395194, 0.0953698
Part.ActiveView().RotateAboutCenter 0.0439104, 0.10098
Part.ActiveView().RotateAboutCenter 0.0131731, 0.0448799
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, 0.0280499
Part.ActiveView().RotateAboutCenter -0.0307373, 0.01122
Part.ActiveView().RotateAboutCenter -0.0395194, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0
Part.ActiveView().RotateAboutCenter -0.0483015, -0.01122
Part.ActiveView().RotateAboutCenter -0.0175642, -0.00560999
Part.SelectByID "Esquisse4@Cage-1@Roulement 20-47", "SKETCH", 0, 0, 0
Part.EditSketch
Part.ClearSelection
Part.SketchConstraintsDel 6, "sgTANGENT"
Part.SketchConstraintsDel 6, "sgTANGENT"
Part.SelectByID "Line18", "SKETCHSEGMENT", 0.001467566975585, 0.005587503773554, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.114167, -0.00560999
Part.ActiveView().RotateAboutCenter 0.21077, -0.0448799
Part.ActiveView().RotateAboutCenter 0.118558, -0.0336599
Part.ActiveView().RotateAboutCenter 0.232725, -0.00560999
Part.ActiveView().RotateAboutCenter 0.122949, 0
Part.ActiveView().RotateAboutCenter 0.100994, 0
Part.ActiveView().RotateAboutCenter 0.0746478, 0
Part.ActiveView().RotateAboutCenter 0.0614746, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0439104, -0.01683
Part.ActiveView().RotateAboutCenter 0.0351284, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ViewZoomTo2 -0.0100626, 0.00495517, -0.0188293, 0.00146757, -0.0149087, -0.0188293
Part.SelectByID "", "EDGE", -0.01367805254813, 0.01553197062553, 0.002808704494392
Part.AndSelectByID "Line18", "SKETCHSEGMENT", -0.003552233223395, 0.005587503773554, 0
Part.DeSelectByID "", "EDGE", -0.01357139802241, 0.01514109314738, 0.002591426101802
Part.AndSelectByID "", "EDGE", -0.01338039107361, 0.01533849701499, 0.002979835279312
Part.ActiveView().RotateAboutCenter -0.0131731, 0
Part.ActiveView().RotateAboutCenter -0.197597, -0.00560999
Part.ActiveView().RotateAboutCenter -0.118558, 0
Part.ActiveView().RotateAboutCenter -0.122949, 0.01122
Part.ActiveView().RotateAboutCenter -0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0878209, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0219552, 0.01683
Part.ViewZoomtofit2
Part.ClearSelection
Part.InsertSketch
Part.EditAssembly
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0395194, 0.1683
Part.ActiveView().RotateAboutCenter 0.0175642, 0.18513
Part.ActiveView().RotateAboutCenter -0.00878209, 0.291719
Part.ActiveView().RotateAboutCenter -0.0395194, 0.409529
Part.ActiveView().RotateAboutCenter -0.12734, 0.695638
Part.ActiveView().RotateAboutCenter -0.100994, 0.314159
Part.ActiveView().RotateAboutCenter -0.0922119, 0.17391
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0526925, 0.218789
Part.ActiveView().RotateAboutCenter -0.100994, 0.409529
Part.ActiveView().RotateAboutCenter -0.0746478, 0.235619
Part.ActiveView().RotateAboutCenter -0.0395194, 0.0841498
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0673198
Part.ActiveView().RotateAboutCenter -0.0439104, 0.14025
Part.ActiveView().RotateAboutCenter -0.0746478, 0.12903
Part.ActiveView().RotateAboutCenter -0.0746478, 0.18513
Part.ActiveView().RotateAboutCenter -0.0702567, 0.14025
Part.ActiveView().RotateAboutCenter -0.0395194, 0.0560999
Part.ActiveView().RotateAboutCenter -0.0395194, 0.0504899
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0673198
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.0614746, 0.280499
Part.ActiveView().RotateAboutCenter -0.0746478, 0.20757
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0392699
Part.ActiveView().RotateAboutCenter -0.0219552, 0.0224399
Part.ActiveView().RotateAboutCenter 0.0131731, -0.01122
Part.ActiveView().RotateAboutCenter 0.0483015, -0.0336599
Part.ActiveView().RotateAboutCenter 0.0526925, -0.0280499
Part.ActiveView().RotateAboutCenter 0.00878209, 0
Part.ActiveView().RotateAboutCenter 0.00439104, 0
Part.ActiveView().RotateAboutCenter 0.0263463, -0.01122
Part.ActiveView().RotateAboutCenter 0.0175642, 0
Part.ActiveView().RotateAboutCenter 0.0219552, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0395194, 0
Part.ActiveView().RotateAboutCenter 0.0219552, 0
Part.ActiveView().RotateAboutCenter 0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0131731, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0307373, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0395194, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0790388, -0.0897598
Part.ActiveView().RotateAboutCenter 0.0702567, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0395194, 0
Part.ActiveView().RotateAboutCenter -0.0439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0834298, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0395194, 0.01122
Part.ActiveView().RotateAboutCenter -0.0439104, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0263463, 0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter -0.00878209, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.0175642, 0.0448799
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0448799
Part.ActiveView().RotateAboutCenter 0, 0.0560999
Part.ActiveView().RotateAboutCenter 0.0263463, 0.0617099
Part.ActiveView().RotateAboutCenter 0.0526925, 0.0617099
Part.ActiveView().RotateAboutCenter 0.0790388, 0.0504899
Part.ActiveView().RotateAboutCenter 0.0307373, 0.0280499
Part.ActiveView().RotateAboutCenter 0.0658657, 0.0392699
Part.ActiveView().RotateAboutCenter 0.0131731, 0.01122
Part.ActiveView().RotateAboutCenter 0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0526925, 0
Part.ActiveView().RotateAboutCenter 0.0351284, 0
Part.ActiveView().RotateAboutCenter 0.0483015, 0
Part.ActiveView().RotateAboutCenter 0.0351284, 0
Part.ActiveView().RotateAboutCenter 0.0395194, -0.0280499
Part.ActiveView().RotateAboutCenter 0.0395194, -0.0560999
Part.ActiveView().RotateAboutCenter 0.0263463, -0.0224399
Part.ActiveView().RotateAboutCenter 0.0175642, -0.01683
Part.ActiveView().RotateAboutCenter 0.00878209, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0560999
Part.ActiveView().RotateAboutCenter 0.0219552, -0.0392699
Part.ActiveView().RotateAboutCenter -0.00439104, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0395194, -0.0448799
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0560999
Part.ActiveView().RotateAboutCenter -0.0307373, -0.0336599
Part.ActiveView().RotateAboutCenter -0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter -0.0175642, -0.01683
Part.ActiveView().RotateAboutCenter -0.00878209, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0219552, -0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0351284, 0.0504899
Part.ActiveView().RotateAboutCenter -0.0526925, 0.0729298
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0224399
Part.ActiveView().RotateAboutCenter -0.0439104, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0175642, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0307373, 0
Part.ActiveView().RotateAboutCenter -0.0263463, -0.01122
Part.ActiveView().RotateAboutCenter -0.0175642, -0.0224399
Part.ActiveView().RotateAboutCenter -0.0263463, -0.01683
Part.ActiveView().RotateAboutCenter -0.0263463, 0.00560999
Part.ActiveView().RotateAboutCenter -0.0307373, 0.0560999
Part.ActiveView().RotateAboutCenter -0.00878209, 0.0280499
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, 0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01122
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.ActiveView().RotateAboutCenter 0.0131731, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.01122
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0617099
Part.ActiveView().RotateAboutCenter 0.00439104, -0.0280499
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0, 0.0280499
Part.ActiveView().RotateAboutCenter 0.0131731, 0.0224399
Part.ActiveView().RotateAboutCenter 0.00878209, 0.0224399
Part.ActiveView().RotateAboutCenter 0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0617099
Part.ActiveView().RotateAboutCenter 0.00439104, -0.01683
Part.ActiveView().RotateAboutCenter 0, -0.01683
Part.ActiveView().RotateAboutCenter -0.00439104, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0131731, 0.0336599
Part.ActiveView().RotateAboutCenter -0.0219552, 0.15708
Part.ActiveView().RotateAboutCenter 0, 0.0224399
Part.ActiveView().RotateAboutCenter 0.0219552, 0.00560999
Part.ActiveView().RotateAboutCenter 0.0878209, -0.0280499
Part.ActiveView().RotateAboutCenter 0.105385, -0.21318
Part.ActiveView().RotateAboutCenter 0.0483015, -0.0785398
Part.ActiveView().RotateAboutCenter 0.0483015, -0.01683
Part.ActiveView().RotateAboutCenter 0.136122, -0.0841498
Part.ActiveView().RotateAboutCenter 0.0483015, -0.0280499
Part.ActiveView().RotateAboutCenter 0.12734, 0.14586
Part.ActiveView().RotateAboutCenter 0.100994, 0.330989
Part.ActiveView().RotateAboutCenter -0.00439104, 0.0504899
Part.ActiveView().RotateAboutCenter -0.0790388, 0.14025
Part.ActiveView().RotateAboutCenter -0.171251, 0.218789
Part.ActiveView().RotateAboutCenter -0.175642, 0.13464
Part.ActiveView().RotateAboutCenter -0.215161, 0.0392699
Part.ActiveView().RotateAboutCenter -0.131731, -0.12903
Part.ActiveView().RotateAboutCenter -0.307373, -0.465629
Part.ActiveView().RotateAboutCenter -0.105385, -0.291719
Part.ActiveView().RotateAboutCenter 0.0175642, -0.0448799
Part.ActiveView().RotateAboutCenter 0.0526925, -0.13464
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.0175642, 0.11781
Part.ActiveView().RotateAboutCenter -0.0526925, 0.16269
Part.ActiveView().RotateAboutCenter -0.100994, -0.0280499
Part.ActiveView().RotateAboutCenter -0.0263463, 0.0785398
Part.ActiveView().RotateAboutCenter -0.00878209, 0.15147
Part.ActiveView().RotateAboutCenter 0, 0.0504899
Part.SelectByID "Bague extérieure-1@Roulement 20-47", "COMPONENT", 0, 0, 0
Part.ClearSelection
' MSGBOX
' Certains des modèles référencés dans ce document ont été modifiés. Ils doivent être enregistrés lorsque le document est enregistré.
' 		Enregistrer le document et les modèles référencés maintenant ?

Part.Save2 FALSE
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
