' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/20/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\Bmw\Boîte de vitesses\came\came.SLDPRT", 1)
Set Part = swApp.ActivateDoc ("came")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ExitApp
End Sub
