' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/06/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\BMW\Boîte de vitesses\came\Fabrication came\Superposition.SLDASM", 2)
Set Part = swApp.ActivateDoc ("Superposition")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.SelectByID "Esquisse1@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.SelectByID "Esquisse3@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.SelectByID "Esquisse3@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.AndSelectByID "Plan1@Brut came-1@Superposition", "PLANE", 0, 0, 0
Part.SelectByID "Esquisse3@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.SelectByID "Dépouille1@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.SelectByID "Dépouille2@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.SelectByID "Dépouille2@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.ActivateSelectedFeature
Part.SelectByID "Dépouille1@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.ActivateSelectedFeature
Part.SelectByID "Congé1@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.SelectByID "Congé1@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.ActivateSelectedFeature
Part.ClearSelection
Part.EditAssembly
Part.SelectByID "Esquisse1@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.SelectByID "Esquisse1@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.ActivateSelectedFeature
Part.SelectByID "Esquisse3@Brut came-1@Superposition", "SKETCH", 0, 0, 0
Part.ClearSelection
Part.SelectByID "Congé1@Brut came-1@Superposition", "BODYFEATURE", 0, 0, 0
Part.ClearSelection
Part.AndSelectByID "", "FACE", 0, 0, 0
Part.AndSelectByID "", "FACE", 0, 0, 0
Part.AndSelectByID "", "FACE", 0, 0, 0
Part.AndSelectByID "", "FACE", 0, 0, 0
Part.AndSelectByID "", "FACE", 0, 0, 0
Part.ActiveView().RotateAboutCenter 0, 0.01122
Part.ActiveView().RotateAboutCenter 0.0411944, 0.280499
Part.ActiveView().RotateAboutCenter 0.0137315, 0.11781
Part.ActiveView().RotateAboutCenter 0.0228858, 0.15708
Part.ActiveView().RotateAboutCenter 0.00915431, 0.0785398
Part.ActiveView().RotateAboutCenter 0.00457715, 0.01122
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter -0.00915431, -0.0504899
Part.ActiveView().RotateAboutCenter -0.0183086, -0.10659
Part.ActiveView().RotateAboutCenter -0.0320401, -0.12342
Part.ActiveView().RotateAboutCenter -0.0137315, -0.20757
Part.ActiveView().RotateAboutCenter -0.0137315, -0.13464
Part.ActiveView().RotateAboutCenter -0.00457715, -0.0448799
Part.ActiveView().RotateAboutCenter 0, -0.00560999
Part.ActiveView().RotateAboutCenter 0, -0.1683
Part.ActiveView().RotateAboutCenter 0, -0.17391
Part.ActiveView().RotateAboutCenter 0, -0.0280499
Part.ActiveView().RotateAboutCenter 0, 0.00560999
Part.ActiveView().RotateAboutCenter 0.00457715, 0.0448799
Part.ActiveView().RotateAboutCenter 0.00457715, 0.10098
Part.ActiveView().RotateAboutCenter 0, 0.0841498
Part.ActiveView().RotateAboutCenter 0, 0.0224399
Part.ActiveView().RotateAboutCenter 0, 0.10659
Part.ActiveView().RotateAboutCenter -0.00457715, 0.0729298
Part.ActiveView().RotateAboutCenter 0, 0.0673198
Part.ActiveView().RotateAboutCenter 0, 0.0673198
Part.ClearSelection
Part.EditAssembly
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
