' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/26/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\BMW\Boîte de vitesses\Arbre de sortie\roulement 6204\Roulements rigides billes 6204b.SLDASM", 2)
Set Part = swApp.ActivateDoc ("Roulements rigides billes 6204b")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ViewDisplayShaded
Part.ActiveView().RotateAboutCenter 0.0401832, -0.0617099
Part.ActiveView().RotateAboutCenter 0.0625071, -0.17952
Part.ActiveView().RotateAboutCenter 0.0357184, -0.12342
Part.ActiveView().RotateAboutCenter 0.0401832, -0.19074
Part.ActiveView().RotateAboutCenter 0.0133944, -0.10098
Part.ActiveView().RotateAboutCenter 0.0044648, -0.10098
Part.ActiveView().RotateAboutCenter 0, -0.258059
Part.ActiveView().RotateAboutCenter 0, -0.263669
Part.ActiveView().RotateAboutCenter 0, -0.246839
Part.ActiveView().RotateAboutCenter 0, -0.482459
Part.ActiveView().RotateAboutCenter -0.00892959, -0.751738
Part.ActiveView().RotateAboutCenter -0.0312536, -0.0897598
Part.ActiveView().RotateAboutCenter 0, 0.0841498
Part.ActiveView().RotateAboutCenter 0.10269, 0.291719
Part.ActiveView().RotateAboutCenter 0.0803663, 0.20757
Part.ActiveView().RotateAboutCenter 0.0357184, 0.0953698
Part.ActiveView().RotateAboutCenter 0.00892959, 0.17952
Part.ActiveView().RotateAboutCenter 0, 0.14586
Part.ActiveView().RotateAboutCenter 0, 0.14586
Part.ActiveView().RotateAboutCenter -0.0133944, 0.0897598
Part.ActiveView().RotateAboutCenter -0.0625071, 0.218789
Part.ActiveView().RotateAboutCenter -0.0312536, 0.347819
Part.ActiveView().RotateAboutCenter -0.0267888, 0.319769
Part.ActiveView().RotateAboutCenter -0.0535775, 0.241229
Part.ActiveView().RotateAboutCenter -0.00892959, 0.01122
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.ActivateDoc ("Part1")
swApp.ExitApp
End Sub
