' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/26/00 by Mady et Jean-Marie REYNAUD
' ******************************************************************************

Dim swApp As Object
Dim Part As Object
Dim Gtol As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()
Set swApp = CreateObject ("SldWorks.Application")
Set Part = swApp.NewPart
Set Part = swApp.ActivateDoc ("Part1")
Set Part = swApp.OpenDoc ("C:\BMW\Boîte de vitesses\Déflecteur\Déflecteur.SLDPRT", 1)
Set Part = swApp.ActivateDoc ("Déflecteur")
Part.SelectByID "Esquisse3", "SKETCH", 0, 0, 0
Part.ActivateSelectedFeature
Part.SelectByID "Esquisse3", "SKETCH", 0, 0, 0
Part.ActivateSelectedFeature
Part.SelectByID "trou de 61", "BODYFEATURE", 0, 0, 0
Part.ActivateSelectedFeature
Part.ViewZoomTo2 -0.151236, -0.00976951, -0.0289294, -0.0662923, -0.0482735, -0.0289294
Part.ActiveView().RotateAboutCenter -0.00450554, -0.00664568
Part.ActiveView().RotateAboutCenter -0.0135166, -0.0265827
Part.ActiveView().RotateAboutCenter -0.0450554, -0.0863938
Part.ActiveView().RotateAboutCenter -0.049561, -0.0598111
Part.ActiveView().RotateAboutCenter -0.0225277, -0.0398741
Part.ActiveView().RotateAboutCenter -0.00901109, -0.019937
Part.ActiveView().RotateAboutCenter -0.0135166, -0.019937
Part.ActiveView().RotateAboutCenter -0.00901109, -0.00664568
Part.ActiveView().RotateAboutCenter -0.0180222, -0.019937
Part.ActiveView().RotateAboutCenter -0.0270333, -0.0398741
Part.ActiveView().RotateAboutCenter -0.0360443, -0.0465197
Part.ActiveView().RotateAboutCenter -0.0405499, -0.0332284
Part.ActiveView().RotateAboutCenter -0.0270333, -0.0132914
Part.ActiveView().RotateAboutCenter -0.0450554, -0.0465197
Part.ActiveView().RotateAboutCenter -0.0675832, -0.0598111
Part.ActiveView().RotateAboutCenter -0.0405499, -0.0265827
Part.ActiveView().RotateAboutCenter -0.0180222, -0.00664568
Part.ActiveView().RotateAboutCenter -0.0450554, -0.00664568
Part.ActiveView().RotateAboutCenter -0.0405499, -0.00664568
Part.ActiveView().RotateAboutCenter -0.0180222, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ActiveView().RotateAboutCenter -0.0135166, 0
Part.ActiveView().RotateAboutCenter -0.0360443, 0
Part.ActiveView().RotateAboutCenter -0.0450554, 0
Part.ActiveView().RotateAboutCenter -0.0225277, 0
Part.ActiveView().RotateAboutCenter -0.0180222, -0.00664568
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.0180222, 0
Part.ActiveView().RotateAboutCenter -0.049561, 0.00664568
Part.ActiveView().RotateAboutCenter -0.0225277, 0
Part.ActiveView().RotateAboutCenter -0.0225277, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0.00664568
Part.ActiveView().RotateAboutCenter -0.0135166, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ActiveView().RotateAboutCenter -0.0135166, 0
Part.ActiveView().RotateAboutCenter 0.00450554, 0.00664568
Part.ActiveView().RotateAboutCenter 0.00450554, 0.00664568
Part.ActiveView().RotateAboutCenter 0.00450554, 0
Part.ActiveView().RotateAboutCenter 0.0135166, 0
Part.ActiveView().RotateAboutCenter 0.00901109, 0.00664568
Part.ActiveView().RotateAboutCenter 0.0180222, 0
Part.ActiveView().RotateAboutCenter 0.00901109, 0
Part.ActiveView().RotateAboutCenter 0.0225277, 0
Part.ActiveView().RotateAboutCenter 0.0180222, 0
Part.ActiveView().RotateAboutCenter 0.0180222, 0.00664568
Part.ActiveView().RotateAboutCenter 0.0450554, 0.00664568
Part.ActiveView().RotateAboutCenter 0.0270333, 0
Part.ActiveView().RotateAboutCenter 0.0405499, 0.0132914
Part.ActiveView().RotateAboutCenter 0.049561, 0.0132914
Part.ActiveView().RotateAboutCenter 0.0180222, 0.00664568
Part.ActiveView().RotateAboutCenter 0.0225277, 0.0132914
Part.ActiveView().RotateAboutCenter 0.0315388, 0.019937
Part.ActiveView().RotateAboutCenter 0.0360443, 0.019937
Part.ActiveView().RotateAboutCenter 0.0315388, 0.0132914
Part.ActiveView().RotateAboutCenter 0.0810998, 0.0398741
Part.ActiveView().RotateAboutCenter 0.0765942, 0.019937
Part.ActiveView().RotateAboutCenter 0.0630776, 0.019937
Part.ActiveView().RotateAboutCenter 0.0630776, 0
Part.ActiveView().RotateAboutCenter 0.0360443, 0.00664568
Part.ActiveView().RotateAboutCenter 0.00450554, 0
Part.ActiveView().RotateAboutCenter 0.00450554, 0
Part.ActiveView().RotateAboutCenter 0.0135166, 0
Part.ActiveView().RotateAboutCenter 0.0720887, 0.0332284
Part.ActiveView().RotateAboutCenter 0.0405499, 0.0265827
Part.ActiveView().RotateAboutCenter 0.0450554, 0.019937
Part.ActiveView().RotateAboutCenter 0.0225277, 0.0132914
Part.ActiveView().RotateAboutCenter 0.0360443, 0.0132914
Part.ActiveView().RotateAboutCenter 0.0225277, 0.0132914
Part.ActiveView().RotateAboutCenter 0, 0.00664568
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0.0132914
Part.ActiveView().RotateAboutCenter -0.0135166, 0.0132914
Part.ActiveView().RotateAboutCenter -0.00901109, 0.0132914
Part.ActiveView().RotateAboutCenter -0.0135166, 0.00664568
Part.ActiveView().RotateAboutCenter -0.0135166, 0
Part.ActiveView().RotateAboutCenter -0.0315388, 0
Part.ActiveView().RotateAboutCenter -0.0270333, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.0225277, 0.00664568
Part.ActiveView().RotateAboutCenter -0.0360443, 0
Part.ActiveView().RotateAboutCenter -0.0405499, 0
Part.ActiveView().RotateAboutCenter -0.0225277, 0
Part.ActiveView().RotateAboutCenter -0.0180222, 0
Part.ActiveView().RotateAboutCenter -0.00901109, 0
Part.ActiveView().RotateAboutCenter -0.00450554, 0
Part.ViewZoomtofit2
Part.ClearSelection
Part.SelectByID "position perçages", "SKETCH", 0, 0, 0
Part.ClearSelection
swApp.ExitApp
End Sub
